apiVersion: v2
name: onecx-ai-provider-ui
version: 0.0.0
description: onecx-ai-provider-ui UI
home: https://github.com/onecx/onecx-ai-provider-ui
keywords:
  - onecx-ai-provider-ui
  - Angular
  - OneCX
sources:
  - https://github.com/onecx/onecx-ai-provider-ui
maintainers:
  - name: OneCX Developer Team
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-angular-app
    version: ^0
    repository: oci://ghcr.io/onecx/charts
    alias: app
