app:
  name: ui
  image:
    repository: onecx/onecx-ai-provider-ui
  routing:
    enabled: true
    path: /mfe/onecxAiUiProvider/
  operator:
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: ./OnecxAiUiProviderModule
          description: OneCX OnecxAiUi Provider Module
          note: OneCX OnecxAiUi Provider UI module auto import via MF operator
          type: MODULE
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-ai-provider-ui
          tagName: onecx-ai-provider-ui-webcomponent
    permission:
      enabled: true
      spec:
        permissions:
          PROVIDER:
            CREATE: Create Provider
            EDIT: Edit Provider
            DELETE: Delete Provider
            SAVE: Update and save Provider
            IMPORT: Import Provider
            EXPORT: Export Provider
            VIEW: View mode for Provider
            SEARCH: Search Provider
            CHANGE_API_KEY: Change ApiKey Provider
          CONFIGURATION:
            CREATE: Create configuration
            EDIT: Edit configuration
            DELETE: Delete configuration
            SAVE: Update and save configuration
            IMPORT: Import configuration
            EXPORT: Export configuration
            VIEW: View mode for configuration
            SEARCH: Search configuration
            BACK: Back to configuration
          MCPSERVER:
            CREATE: Create mcpserver
            EDIT: Edit mcpserver
            DELETE: Delete mcpserver
            SAVE: Update and save mcpserver
            IMPORT: Import mcpserver
            EXPORT: Export mcpserver
            VIEW: View mode for mcpserver
            SEARCH: Search mcpserver
            BACK: Navigate back in details of mcpserver
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: onecx-ai-provider-ui
